# NOTE: Only run this workflow when the Markdown docs are updated!!!
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4 # clones my git repo to the runner so that it can perform stuff

      # Download hugo to the runner
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      # Runs the command to make the static files and put it in the public directory
      - name: Build the static files
        run: hugo -t contrast-hugo

      # Go to the public directory and push changes to the submodule repo
      - name: Push static files to submodule repo
        run: |
          cd public
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update from CI workflow in blogs repository"
          git push 

      # Go back to the parent repo and update it to point to the new commit of the submodule repo
